# Load additional configuration files (to override what's defined here)
load-additional-configuration: shared/classes/crafter/studio/configuration.yml

# Git repository base path (all actual repositories will be under this)
git-repo-base: repos
# Global git repository path
global-repo-path: global
# Sites repositories base path
sites-repo-path: sites
# Sandbox git repository name under every site
sandbox-path: sandbox
# Published git repository name under every site
published-path: published