version: ~> 1.0
dist: focal
language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
git:
  depth: 1
  quiet: true
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
install: skip
script:
  - echo `pwd`
  - pushd .
  - cd /home/travis
  - wget -q https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz
  - tar xvzf openjdk-11+28_linux-x64_bin.tar.gz
  - export JAVA_HOME=/home/travis/jdk-11
  - export PATH=/home/travis/jdk-11/bin:$PATH
  - popd
  - which java
  - java -version
  - mvn -version
#  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn -q -Dmaven.javadoc.skip=true clean deploy -DcloneUi=true --settings .travis-settings.xml; else mvn -q -Dmaven.javadoc.skip=true clean install -DcloneUi=true ;fi
  - mvn -q -Dmaven.javadoc.skip=true clean deploy -DcloneUi=true --settings .travis-settings.xml
env:
  global:
  - secure: ccvaP/HRa4Taolqr0RX0xcJLXtRCRtyqLLs3EGfC7pAFQ0q0hfiYKyRFTPPsZ9wzrE7ozb31AaCJFDZo9S1/clzAGCJccAENyIj36RTuF3EQYZkFKSoeHOTeCMuC3k+ZiDzKWGdGwo54lSlNZNx1yQVGCK5dE+y4f9e2d7wR3Kk=
  - secure: JeNNkqjucCFDU//OwUVLLp3Ru//9L4nyym9bsuHiL4aaoXc4+IAtodGw8mnpZ6c/XTsILeJ9O5iUaMOKUQy6PTtSOyGBejVn2FNeQnYr6tJDyioSy1f0cPQeL6R5MF3AOIIDZwYcCpy/aN6dGYB8+V/Jv9bTPEFnn0CUUKIR10g=
