version: ~> 1.0
language: java
jdk:
- openjdk11
git:
  depth: 1
  quiet: true
branches:
  only:
  - develop
  - support/.*
  - master
cache:
  directories:
    - $HOME/.m2
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script: build.sh
env:
  global:
  - secure: ccvaP/HRa4Taolqr0RX0xcJLXtRCRtyqLLs3EGfC7pAFQ0q0hfiYKyRFTPPsZ9wzrE7ozb31AaCJFDZo9S1/clzAGCJccAENyIj36RTuF3EQYZkFKSoeHOTeCMuC3k+ZiDzKWGdGwo54lSlNZNx1yQVGCK5dE+y4f9e2d7wR3Kk=
  - secure: JeNNkqjucCFDU//OwUVLLp3Ru//9L4nyym9bsuHiL4aaoXc4+IAtodGw8mnpZ6c/XTsILeJ9O5iUaMOKUQy6PTtSOyGBejVn2FNeQnYr6tJDyioSy1f0cPQeL6R5MF3AOIIDZwYcCpy/aN6dGYB8+V/Jv9bTPEFnn0CUUKIR10g=
