      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 'Project ID, unique and immutable'
        name:
          type: string
          description: 'Project name, unique within an organization and can be changed'
        desc:
          type: string
          description: Project description
        liveUrl:
          type: string
          description: >-
            Project live URL, where is project can be accessed or downloaded (if
            app)
        previewUrl:
          type: string
          description: Project preview URL in Crafter Studio
        stagingUrl:
          type: string
          description: >-
            Project staging URL, where major update can be staged before pushing
            live
