openapi: 3.0.0
servers:
  - url: 'http://localhost:8080/studio/api/3'
info:
  description: |-
    Crafter Studio API v3
    https://docs.craftercms.org/en/3.0/developers/projects/studio/index.html
  version: '3 Alpha'
  title: Crafter Studio
  termsOfService: ''
  contact:
    email: info@craftercms.org
  license:
    name: GPL 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
externalDocs:
  description: Crafter CMS - Studio
  url: 'https://docs.craftercms.org/en/3.0/developers/projects/studio/index.html'
tags:
  - name: user
    description: User management operations
  - name: organization
    description: Organization management operations

paths:
  $ref: 'https://raw.githubusercontent.com/craftercms/studio/develop/src/main/api/3/paths/index.yaml'

components:
  $ref: 'https://raw.githubusercontent.com/craftercms/studio/develop/src/main/api/3/components/index.yaml'