openapi: 3.0.0
servers:
  - url: 'http://localhost:8080/studio/api/3'
info:
  description: |-
    Crafter Studio API v3
    https://docs.craftercms.org/en/3.0/developers/projects/studio/index.html
  version: '3 Alpha'
  title: Crafter Studio
  termsOfService: ''
  contact:
    email: info@craftercms.org
  license:
    name: GPL 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
externalDocs:
  description: Crafter CMS - Studio
  url: 'https://docs.craftercms.org/en/3.0/developers/projects/studio/index.html'
tags:
  - name: user
    description: User management operations
  - name: organization
    description: Organization management operations

paths:
  $ref: 'https://raw.githubusercontent.com/craftercms/studio/develop/src/main/api/3/paths/index.yaml'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 'User ID, unique user-identifier, immutable'
        username:
          type: string
          description: 'Username, unique but can be changed'
        firstName:
          type: string
          description: User's first name
        lastName:
          type: string
          description: User's last name
        email:
          type: string
          description: User's email address
        password:
          type: string
          description: User's password
        avatar:
          type: string
          description: 'User''s avatar, base64 encoded image @128x128 pixel PNG'
        status:
          type: string
          description: User status. See relevant LoV for user status.
    LoV:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: List of Values ID
        lov:
          description: List of key-value pairs
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
    Organization:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 'Organization ID, unique and immutable'
        name:
          type: string
          description: 'Organization name, unique and can be changed'
        desc:
          type: string
          description: Organization description
        url:
          type: string
          description: Organization URL (usually the organization WebSite)
        logo:
          type: string
          description: 'Organization logo, base64 encoded image @128x128 pixel PNG'
    Group:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 'Group ID, unique and immutable'
        name:
          type: string
          description: 'Group name, unique within an organization and can be changed'
        desc:
          type: string
          description: Group description
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 'Project ID, unique and immutable'
        name:
          type: string
          description: 'Project name, unique within an organization and can be changed'
        desc:
          type: string
          description: Project description
        liveUrl:
          type: string
          description: >-
            Project live URL, where is project can be accessed or downloaded (if
            app)
        previewUrl:
          type: string
          description: Project preview URL in Crafter Studio
        stagingUrl:
          type: string
          description: >-
            Project staging URL, where major update can be staged before pushing
            live
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 'Item ID, unique and immutable'
        orgId:
          type: string
          description: The organization to which the project that holds the item blongs
        projectId:
          type: string
          description: Project ID to which this item belongs
        path:
          type: string
          description: Path of item in the project's repository
        state:
          type: string
          description: Item state. See relevant LoV for item states.
        type:
          type: string
          description: Item type. See relevant LoV for item types.
        mimetype:
          type: string
          description: >-
            MIME-Type if the item is a file. See relevant LoV for item
            MIME-Types.
        createdBy:
          type: string
          description: UserId of creator
        createdOn:
          type: string
          description: Date of creation
        lastModifiedBy:
          type: string
          description: UserId of last modifier
        lastModifiedOn:
          type: string
          description: Date of last modification
        commitId:
          type: string
          description: Last repository commit_id
    Policy:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Policy ID
        version:
          type: string
          description: Policy version number
        statements:
          type: array
          items:
            type: object
            properties:
              effect:
                type: string
                enum:
                  - allow
                  - deny
                example: allow
                description: Allow or Deny
              actions:
                type: array
                items:
                  type: string
                  description: >-
                    See relevant LoV for actions using
                    system:service:resourcetype [TODO explain]
              resource:
                type: string
                example: >-
                  crn:studio:content:0284a098aab7c7:130880c018310810b:item:static-assets/*
                description: See TODO
    Role:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 'Role ID, unique and immutable'
        name:
          type: string
          description: 'Role name, unique within ?? TODO'
        policies:
          type: array
          items:
            $ref: '#/components/schemas/Policy'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        remedialAction:
          type: string
        documentationUrl:
          type: string
      required:
        - code
        - message
  parameters:
    offsetParam:
      name: offset
      in: query
      description: Number of items to skip before returning the results.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
    limitParam:
      name: limit
      in: query
      description: Number of items to return.
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 10
  requestBodies:
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      description: List of user object
      required: true
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
            example: 'responseCode = 1000, responseMessage = blah'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiResponse'
  securitySchemes: null
  links: {}
  callbacks: {}
security: []
